### ISSUE TITLE
A problrm about the model "a_transformers"

### ISSUE THREAD

**Issue by RaisnnowLawrence** [YunxinLi/Multimodal-Context-Reasoning#1]
Hello, I am having a problem running the code "run_PMR_ModCR.py" and the error is reported as follows:
```
Traceback (most recent call last):
  File "run_PMR_ModCR.py", line 21, in <module>
    from modeling.modeling_transfomres import BertImgModel
  File "/home/stormai/userfile/lizhengxue/WorkOnModCR/Multimodal-Context-Reasoning-main/modeling/modeling_transfomres.py", line 8, in <module>
    from a_transformers.modeling_bert import (BertEmbeddings,
ModuleNotFoundError: No module named 'a_transformers'
```
Where does the model "a_transformers" come from? And how do I use it?
In addition: What does the zip package "local_transformers.zip" do?
Thanks you!

**Comment by YunxinLi** [comment]
Sorry, Its my oversight. Now I have upload the a_transformers.zip. 
local_transformers.zip: the package of the used transformer library. 
we mainly modify the way Roberta model incorporates prefix vectors.

**Comment by RaisnnowLawrence** [comment]
Thanks, the problem has been solved
