### ISSUE TITLE
A question about PMR dataset

### ISSUE THREAD

**Issue by RaisnnowLawrence** [YunxinLi/Multimodal-Context-Reasoning#2]
Hello.
I encountered the following error when running the run_PMR_ModCR.py folder:
```
Traceback (most recent call last):
  File "run_PMR_ModCR.py", line 930, in <module>
    main()
  File "run_PMR_ModCR.py", line 840, in main
    train_dataset = PMR_ChunkAlign_Dataset_align_ensemble_T(tokenizer, gpt_tokenizer, roberta_tokenizer,
  File "/home/stormai/userfile/lizhengxue/WorkOnModCR/Multimodal-Context-Reasoning-main/Data/VCRChunkAlign.py", line 542, in __init__
    self.VCR_annot_dict = pickle.load(open(VCR_example_file, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'pmr_data/ex_feature/train_CALeC_ori-o.pkl'
```
Where do I get the "train_CALeC_ori-o.pkl" file?

**Comment by YunxinLi** [comment]
These data source are preprocessed by the FasterRCNN to support the input of Oscar. I will upload them to the corresponding huggingface repository soon.

**Comment by YunxinLi** [comment]
Some preprocessed data are shown in data_feature.zip 
Link: https://huggingface.co/YunxinLi/ModCR_checkpoints/tree/main
Note: the image feature of VCR train set are too big (about 90G), thus the corresponding image feature stored in pmr_image_feature(data_feature.zip) may miss some data.

**Comment by RaisnnowLawrence** [comment]
Thank you very much!
