### ISSUE TITLE
Multi-View-Reasoning-cold-start-1-0.19700910273081926-755.pth can not found

### ISSUE THREAD

**Issue by Gary-code** [YunxinLi/Multimodal-Context-Reasoning#6]
I use the checkpoint Multi-View-Reasoning-cold-start-1.pth instead to run PMR dataset. An error occurs when loading the model: 

Error(s) in loading state_dict for Abstract_Specific: size mismatch for classifier.weight: copying a param with shape torch.Size([1, 2304]) from checkpoint, the shape in current model is torch.Size([1, 1536]).

Looking forwards to your reply

**Comment by YunxinLi** [comment]
This cold start parameter is useless, you could delete this parameter and initialize this parameter randomly.

**Comment by YunxinLi** [comment]
In 823-830 lines, you could add following codes to delete it.
``if 'classifier.' in n:
    del params[n]
``

**Comment by Gary-code** [comment]
Thanks, I will try later. Nice work in ACL 2023.
